inherit_from: .rubocop_todo.yml

# inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 130

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Exclude:
    - lib/tasks/import.rake
    - spec/rails_helper.rb
    - spec/spec_helper.rb
