language: ruby
rvm:
  - 2.5.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - gem update bundler
  - psql -c 'create database hidden_collections_test;' -U postgres
  - bundle install
  - bundle exec rake db:test:prepare
script:
  - bundle exec rake ci
sudo: false
cache: bundler
bundler_args: --without production
