language: ruby
rvm:
- 2.5.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
- gem update --system
- gem install bundler
- psql -c 'create database hidden_collections_test;' -U postgres
- bundle install
- bundle exec rake db:test:prepare
script:
- bundle exec rake ci
sudo: false
cache: bundler
bundler_args: "--without production"
deploy:
  provider: heroku
  app: dlf-voting-app
  run:
  - rake db:migrate
  - restart
  api_key:
    secure: SDbnnZa8wFoUCKi0wOwqBIQLZXIVLvqxq/qeRX7ufkXfBe3DOrTrnOteW6wzMgeY4i31g9qFpe95gsCz8UxPasVs1izzKlXagOaSR5QzsgE6Wwgjxk6vR1zh5XENwcLmMAt88SDLcKNfOs8gEq7NZFL4w2OGROuBZvnh+rhLfJncdB15v25FIzjDyihpdeXb2JQEsVd3rueijSKMyZ3ntD6xK4JdFi0pwIS/L0s4Esy+BvD0kRZn2r7rOAf6qDc45XEoZPicsCfCGzaHHYJ+EGMQVr1iUDKr7vNdenZ3A59FKocBrNelWKpNJLLPZdsZAPe5c5stftd9u9JKzENOLt9rFeLCqf++6agyM74EUmsw53LgNEEg9Ct6vEmElm9up+pO1o+P4vn6FDgXhd3DmiW5+i21aE8P6SYpxKinEmm8vskEs3h3H7Ln3vo8p1Iy1lpDbX9VLqphQRd2+vKFCf0qi5xwoLmYJe/WWny3TSYCUyCnTh3QOtsdHy+DisZrsvrtqj1761QCNOJH3C/LVfMipHDUoqSWIC9+lL2UyDeobgYq/+a5mUIHTDoXcL9mFej5XmrXCLGpulvAQ8m7stxYb8t+BnCXxKPw4qsYjzIt/7VOznN9HZ7xdvU8r742zt1/9JXLVSwvsY1GrUOTT5I8xYWeVC+IuP5ojjYXiGw=
