language: ruby
rvm:
  - 2.7.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - gem install bundler
  - yes | gem update --system --force
script:
  - bundle exec rake ci
sudo: false
services:
  - postgresql
cache: bundler
before_script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:mirate --trace
bundler_args: "--without production"
deploy:
  provider: heroku
  app: dlf-voting-app
  run:
  - rake db:migrate
  - restart
  api_key:
    secure: JklisupzOow3FpYsyJm9g7r/wC5PIMfV2qfvALyAUXJpxLMYZixIHYzNJFvd4LcK4L61stKfPolPSQZRj8V9VPGIxEqEg7HM+kk3LHXTGIXIrvC9kdKPvff7udK90cQ39NMt7wFpbPSMOcXeerxhkKHrmWB8fk4wJYHgZeBuF2hOmwgC/I3IVnaBSjVGLBHBDATFq5ldoz9LYwbkFfo1zVUth2vbvGgBfYZXNo0EtI2QfJCRplmaj7oRDKoyB4RfHf5zoVQ/42uBqsuVhu8G702Vxsd38Ek0vxAyyv8UBQJFtAsPcbt9NUoW5obu4KLKgM/EVa6cNyClcIKmH09mmqP3CgRNf9DPsfn3XN83luRxELXjSbGy3MQVGIPtB0QShBxAUb9tauzQObnyqKQiuhEOOQV1LoKmQO78fERE72ZZN8hE+SSAob5FY4d91GzzUQ/HTOMM23RamOQduyegSLUaeVIDOKZwbic3JnGN2h1OmSmuBaO3CSjjuiHP7fnUsdFuydmdNHV3fL5U9jEoX3T0988f7a5niaOcxCSz0IDyGV7pCOBY1TutV79lJ6+f7lvqQL3NpQ+qaN1tW8QnkqBUfaJrO8um1j9trieY0deVqBcuNhviarajqLXxpn0K12/A/GaDBZKZUrnhc5Ey4u2yEDcc8INtEVP2Jgex0xU=
