language: ruby
rvm:
  - 3.0
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  update: true
  chrome: stable
before_install:
  - gem install bundler
  - npm update -g npm
  - yes | gem update --system --force
script:
  - bundle exec rake spec
sudo: false
services:
  - postgresql
cache:
  bundler: true
  directories:
    - ~/.webdrivers
before_script:
  - psql -c 'create database participatory_voter_test;' -U postgres
  - bundle exec rake db:migrate --trace
  - yarn install --ignore-engines
bundler_args: "--without production"
