# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 163f6cf92eeec35144b5e6fd361810e35afcdec00fafa9b9aaa849a4047047a99a7bb74f1a30fdaec1742a856e5d59936f7919211e1373dacb85b562022f527c

test:
  secret_key_base: d6638379c4f54d60e2ecf94e417c492d92f2c53183380cb6d967410532e6b751195b967abb1f685e81b674fb35ad4a360467ac9291be1e167769cb0e5446b008

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
